## EDA on Property and Casualty Data

In [74]:
# Here is an explanation of the columns: https://www.kaggle.com/code/zainawan27/exploratorydataanalysisinsurance

In [1]:
# import libraries
import pandas as pd

In [2]:
# Import data
filename = '~/Documents/Software/DevFile/Property&CasualtyInsurance/finalapi.csv'
pdf_data = pd.read_csv(filename)
print(pdf_data.shape)
pdf_data

(213328, 49)


AGENCY_ID  PRIMARY_AGENCY_ID   PROD_ABBR PROD_LINE STATE_ABBR  \
0               3                  3  BOILERMACH        CL         IN   
1               3                  3  BOILERMACH        CL         IN   
2               3                  3  BOILERMACH        CL         IN   
3               3                  3  BOILERMACH        CL         IN   
4               3                  3  BOILERMACH        CL         IN   
...           ...                ...         ...       ...        ...   
213323       9998               9998  PERSUMBREL        PL         IN   
213324       9998               9998  PERSUMBREL        PL         IN   
213325       9998               9998  PERSUMBREL        PL         KY   
213326       9998               9998  PERSUMBREL        PL         KY   
213327       9998               9998  PERSUMBREL        PL         KY   

        STAT_PROFILE_DATE_YEAR  RETENTION_POLY_QTY  POLY_INFORCE_QTY  \
0                         2005                   0                 0   
1                         2006                   0                 0   
2                         2007                   0                 0   
3                         2008                   0                 0   
4                         2009                   0                 0   
...                        ...                 ...               ...   
213323                    2014                  39                39   
213324                    2015                  15                15   
213325                    2013                   0                 9   
213326                    2014                   9                12   
213327                    2015                   5                 5   

        PREV_POLY_INFORCE_QTY  NB_WRTN_PREM_AMT  ...  PL_BOUND_CT_ELINKS  \
0                           0             40.00  ...                   0   
1                           0            151.00  ...                   0   
2                           0             40.00  ...                   0   
3                           0             69.00  ...                   0   
4                           0             28.00  ...                   0   
...                       ...               ...  ...                 ...   
213323                     60              0.00  ...                   0   
213324                     18              0.00  ...                   0   
213325                  99999            132.19  ...                   0   
213326                      9              0.00  ...                   0   
213327                      5              0.00  ...                   0   

        PL_QUO_CT_ELINKS  PL_BOUND_CT_PLRANK  PL_QUO_CT_PLRANK  \
0                      0                   0               103   
1                      0                   0               103   
2                      0                   0               103   
3                      0                   0               103   
4                      0                   0               103   
...                  ...                 ...               ...   
213323                 0                   0                 0   
213324                 0                   0                 0   
213325                 0                   0                 0   
213326                 0                   0                 0   
213327                 0                   0                 0   

        PL_BOUND_CT_eQTte  PL_QUO_CT_eQTte  PL_BOUND_CT_APPLIED  \
0                      50              288                    0   
1                      50              288                    0   
2                      50              288                    0   
3                      50              288                    0   
4                      50              288                    0   
...                   ...              ...                  ...   
213323                 22              136                    0   
213324                 2

In [3]:
# Examine the column names, if any nulls, and data types
pdf_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213328 entries, 0 to 213327
Data columns (total 49 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   AGENCY_ID                  213328 non-null  int64  
 1   PRIMARY_AGENCY_ID          213328 non-null  int64  
 2   PROD_ABBR                  213328 non-null  object 
 3   PROD_LINE                  213328 non-null  object 
 4   STATE_ABBR                 213328 non-null  object 
 5   STAT_PROFILE_DATE_YEAR     213328 non-null  int64  
 6   RETENTION_POLY_QTY         213328 non-null  int64  
 7   POLY_INFORCE_QTY           213328 non-null  int64  
 8   PREV_POLY_INFORCE_QTY      213328 non-null  int64  
 9   NB_WRTN_PREM_AMT           213328 non-null  float64
 10  WRTN_PREM_AMT              213328 non-null  float64
 11  PREV_WRTN_PREM_AMT         213328 non-null  float64
 12  PRD_ERND_PREM_AMT          213328 non-null  float64
 13  PRD_INCRD_LOSSES_AMT       21

In [4]:
# Examine the numberical columns
pdf_data.describe()

AGENCY_ID  PRIMARY_AGENCY_ID  STAT_PROFILE_DATE_YEAR  \
count  213328.000000      213328.000000           213328.000000   
mean     4978.964158       21840.982206             2010.191738   
std      2928.027642       36410.355440                3.129108   
min         3.000000           3.000000             2005.000000   
25%      2366.000000        2788.000000             2008.000000   
50%      4976.000000        6110.000000             2010.000000   
75%      7589.000000        9285.000000             2013.000000   
max      9998.000000       99999.000000             2015.000000   

       RETENTION_POLY_QTY  POLY_INFORCE_QTY  PREV_POLY_INFORCE_QTY  \
count       213328.000000     213328.000000          213328.000000   
mean           158.634525        175.616919            6694.153369   
std            718.766295        774.640860           24639.586044   
min              0.000000          0.000000               0.000000   
25%              0.000000          0.000000               0.000000   
50%              0.000000          0.000000               0.000000   
75%             24.000000         30.000000              72.000000   
max          21979.000000      22968.000000           99999.000000   

       NB_WRTN_PREM_AMT  WRTN_PREM_AMT  PREV_WRTN_PREM_AMT  PRD_ERND_PREM_AMT  \
count     213328.000000   2.133280e+05        2.133280e+05       2.133280e+05   
mean        2243.651368   1.963268e+04        2.600812e+04       1.945872e+04   
std         9976.801667   6.644395e+04        7.008093e+04       6.635115e+04   
min            0.000000  -2.027776e+05       -1.861810e+05      -1.643490e+05   
25%            0.000000   2.027500e+00        1.480000e+02       7.600000e+01   
50%            0.000000   1.143620e+03        1.781000e+03       1.180490e+03   
75%          485.000000   8.358695e+03        1.477315e+04       8.231562e+03   
max       556930.220000   1.715742e+06        1.904570e+06       1.780498e+06   

       ...  PL_BOUND_CT_ELINKS  PL_QUO_CT_ELINKS  PL_BOUND_CT_PLRANK  \
count  ...       213328.000000     213328.000000       213328.000000   
mean   ...        26928.162206      26969.472127        26931.800401   
std    ...        44357.460628      44333.186665        44355.256891   
min    ...            0.000000          0.000000            0.000000   
25%    ...            0.000000          0.000000            0.000000   
50%    ...            0.000000          0.000000            0.000000   
75%    ...        99999.000000      99999.000000        99999.000000   
max    ...        99999.000000      99999.000000        99999.000000   

       PL_QUO_CT_PLRANK  PL_BOUND_CT_eQTte  PL_QUO_CT_eQTte  \
count     213328.000000      213328.000000    213328.000000   
mean       27039.756497       26963.478081     27091.403323   
std        44291.273197       44336.059501     44258.970692   
min            0.000000           0.000000         0.000000   
25%            0.000000          11.000000        66.000000   
50%            0.000000          51.000000       258.000000   
75%        99999.000000       99999.000000     99999.000000   
max        99999.000000       99999.000000     99999.000000   

       PL_BOUND_CT_APPLIED  PL_QUO_CT_APPLIED  PL_BOUND_CT_TRANSACTNOW  \
count        213328.000000      213328.000000            213328.000000   
mean          26928.081002       26933.596284             26927.300134   
std           44357.509786       44354.180214             44357.983442   
min               0.000000           0.000000                 0.000000   
25%               0.000000           0.000000                 0.000000   
50%               0.000000           0.000000                 0.000000   
75%           99999.000000       99999.000000             99999.000000   
max           99999.000000       99999.000000             99999.000000   

       PL_QUO_CT_TRANSACTNOW  
count          213328.000000  
mean            26927.453377  
std             44357.890447  
min                 0.000000  
25%    

Many columns have 9998 or 9999 as their max value. These require more investigation.

In [5]:
# How many unique AGENCY_ID's?

print(f"The number of unique agencies: {pdf_data['AGENCY_ID'].nunique()}")

The number of unique agencies: 1623


In [10]:
# Concatenate the state and agency number (default is duplicated within state)
# pdf_data['AGENCY_ID'].describe()  # Checking the number of digits

pad_width = 6
pdf_data['state_agency'] = pdf_data['STATE_ABBR'].astype(str) +\
pdf_data['AGENCY_ID'].astype(str).str.zfill(pad_width)
print(pdf_data['state_agency'].nunique())

2937


## Investigating 9998 and 9999 values

In [11]:
# Figure out how many 9998 or 9999 values are present in each column.

dct_missing_values = {}

for i in pdf_data:
    dct_missing_values[i] = {}
    dct_missing_values[i]['9998'] = pdf_data[i].isin([9998]).sum().item()
    dct_missing_values[i]['9999'] = pdf_data[i].isin([9999]).sum().item()
    dct_missing_values[i]['99999'] = pdf_data[i].isin([99999]).sum().item()
dct_missing_values   

{'AGENCY_ID': {'9998': 342, '9999': 0, '99999': 0},
 'PRIMARY_AGENCY_ID': {'9998': 342, '9999': 0, '99999': 37874},
 'PROD_ABBR': {'9998': 0, '9999': 0, '99999': 0},
 'PROD_LINE': {'9998': 0, '9999': 0, '99999': 0},
 'STATE_ABBR': {'9998': 0, '9999': 0, '99999': 0},
 'STAT_PROFILE_DATE_YEAR': {'9998': 0, '9999': 0, '99999': 0},
 'RETENTION_POLY_QTY': {'9998': 0, '9999': 0, '99999': 0},
 'POLY_INFORCE_QTY': {'9998': 1, '9999': 1, '99999': 0},
 'PREV_POLY_INFORCE_QTY': {'9998': 1, '9999': 1, '99999': 13893},
 'NB_WRTN_PREM_AMT': {'9998': 0, '9999': 1, '99999': 1},
 'WRTN_PREM_AMT': {'9998': 0, '9999': 0, '99999': 0},
 'PREV_WRTN_PREM_AMT': {'9998': 0, '9999': 0, '99999': 13893},
 'PRD_ERND_PREM_AMT': {'9998': 0, '9999': 0, '99999': 0},
 'PRD_INCRD_LOSSES_AMT': {'9998': 0, '9999': 0, '99999': 0},
 'MONTHS': {'9998': 0, '9999': 0, '99999': 0},
 'RETENTION_RATIO': {'9998': 0, '9999': 0, '99999': 129978},
 'LOSS_RATIO': {'9998': 0, '9999': 0, '99999': 51232},
 'LOSS_RATIO_3YR': {'9998': 0, '

In [12]:
# Examine the rows that contain 9999 values
# Turn lines on or off as needed

# pdf_data[pdf_data['PREV_POLY_INFORCE_QTY'] == 9999]
# pdf_data[pdf_data['PREV_POLY_INFORCE_QTY'] == 9998]
pdf_data[pdf_data['NB_WRTN_PREM_AMT'] == 9999]

AGENCY_ID  PRIMARY_AGENCY_ID PROD_ABBR PROD_LINE STATE_ABBR  \
17693        811                811  WORKCOMP        CL         KY   

       STAT_PROFILE_DATE_YEAR  RETENTION_POLY_QTY  POLY_INFORCE_QTY  \
17693                    2005                   0                 0   

       PREV_POLY_INFORCE_QTY  NB_WRTN_PREM_AMT  ...  PL_QUO_CT_ELINKS  \
17693                      0            9999.0  ...                 5   

       PL_BOUND_CT_PLRANK  PL_QUO_CT_PLRANK  PL_BOUND_CT_eQTte  \
17693                   0                 0                 17   

       PL_QUO_CT_eQTte  PL_BOUND_CT_APPLIED  PL_QUO_CT_APPLIED  \
17693               78                    5                 34   

       PL_BOUND_CT_TRANSACTNOW  PL_QUO_CT_TRANSACTNOW  state_agency  
17693                        0                      0      KY000811  

[1 rows x 50 columns]

### Conclusion Regarding 9998 or 9999 or 99999 values

There does not appear to be very many 9998 or 9999. 
There are many more 99999 values. Replace with NaN.

In [13]:
# Replace rows containing the 9998 or 9999 values
# It's easiest to replace all values with nan and then drop rows containing a null
import numpy as np

print(f"The shape of pdf_data BEFORE inserting nulls: {pdf_data.shape}")

for i in pdf_data:
    pdf_data[i] = pdf_data[i].replace(9998, np.nan)
    pdf_data[i] = pdf_data[i].replace(9999, np.nan)
    pdf_data[i] = pdf_data[i].replace(99999, np.nan)


# pdf_data = pdf_data.dropna()
print(f"The shape of pdf_data AFTER inserting nulls: {pdf_data.shape}")

The shape of pdf_data BEFORE inserting nulls: (213328, 50)
The shape of pdf_data AFTER inserting nulls: (213328, 50)


## Looking for Duplicate Rows

In [14]:
# Looking for duplicates
duplicates = pdf_data.duplicated()
duplicates.sum().item()

0

## Examine the categorical variables

In [15]:
# Examine the categorical variables

l_cat_vars = ['state_agency','PROD_ABBR','PROD_LINE','STATE_ABBR','VENDOR_IND','VENDOR']
dct_unique = {}

# Get a count of each unique value for each of the variables
for i in l_cat_vars:
    dct_unique[i] = {}
    dct_unique[i]['Values'] = pdf_data[i].unique()
    for k in dct_unique[i]['Values']:
        dct_unique[i][k] = len(pdf_data[pdf_data[i]==k])
dct_unique

{'state_agency': {'Values': array(['IN000003', 'KY000003', 'MI000003', ..., 'IN009998', 'KY009998',
         'OH009998'], shape=(2937,), dtype=object),
  'IN000003': 228,
  'KY000003': 193,
  'MI000003': 6,
  'OH000003': 60,
  'PA000003': 19,
  'WV000003': 5,
  'IN000011': 96,
  'WV000011': 3,
  'KY000011': 4,
  'KY000012': 38,
  'IN000012': 7,
  'OH000014': 6,
  'OH000016': 204,
  'WV000016': 62,
  'OH000032': 166,
  'WV000032': 8,
  'PA000036': 130,
  'WV000037': 23,
  'OH000046': 221,
  'PA000046': 5,
  'PA000061': 64,
  'OH000084': 40,
  'OH000087': 208,
  'PA000093': 4,
  'KY000096': 155,
  'KY000099': 14,
  'KY000102': 117,
  'OH000102': 46,
  'WV000102': 30,
  'PA000111': 85,
  'OH000111': 8,
  'PA000123': 8,
  'KY000125': 6,
  'PA000130': 5,
  'MI000134': 4,
  'IN000148': 168,
  'KY000148': 8,
  'OH000152': 221,
  'OH000153': 36,
  'KY000156': 94,
  'MI000156': 7,
  'OH000156': 226,
  'WV000156': 61,
  'IN000156': 9,
  'OH000160': 8,
  'PA000160': 16,
  'OH000163': 47,
  'IN000

In [16]:
## Output final dataset

filename = 'agency_performance_final.csv'
pdf_data.to_csv(filename, index=False)